CREATE TABLE CLIENT 
(
  CLIENTID NUMBER NOT NULL 
, CLIENTNAME NVARCHAR2(50) NOT NULL 
, CLIENTCODE NVARCHAR2(20) NOT NULL 
, STREETNAME1 NVARCHAR2(50) 
, STREETNAME2 NVARCHAR2(50) 
, CITY NVARCHAR2(20) 
, STATE NVARCHAR2(20) 
, COUNTRY NVARCHAR2(20) 
, ZIPCODE NVARCHAR2(20) 
, CONTACTNAME NVARCHAR2(50) NOT NULL 
, CONTACTEMAIL NVARCHAR2(50) 
, CONTACTCELL NVARCHAR2(50) 
, CONTACTPHONE NVARCHAR2(50) 
, CONSTRAINT CLIENT_PK PRIMARY KEY 
  (
    CLIENTID 
  )
  ENABLE 
);

COMMENT ON COLUMN CLIENT.CLIENTID IS 'auto increment';
